Repository recognai/biome-text, pull requests merged in 2020-10, with the labels that each got.

#384 Replace call to non-existent _default_ds_mapping attribute
  src/biome/text/pipeline.py
  tests/text/test_pipeline_explore.py
Labels: bugfix

#386 Output entities for token classification
  src/biome/text/helpers.py
  src/biome/text/modules/heads/task_head.py
  src/biome/text/modules/heads/token_classification.py
  tests/text/modules/heads/test_token_classification.py
Labels: enhancement

#387 initial records sorted by default
  ui/src/assets/scss/apps/classifier/explain.scss
  ui/src/components/common/FiltersList.vue
  ui/src/components/elements/core/reSortList/reSortList.vue
  ui/src/components/mixins/MixinClassifier.js
Labels: UI, enhancement

#394 Add `max_length` parameter to transformers feature
  src/biome/text/features.py
  tests/text/test_features_transformers.py
Labels: enhancement

#391 fix vulnerabilities in dependencies
  ui/package.json
Labels: bugfix
